### ISSUE TITLE
Instructions for Inspec for EXSI 7 servers and VCSA Server

### ISSUE THREAD

**Issue by LunaireRae** [vmware/dod-compliance-and-automation#107]
### Is your feature request related to a problem? Please describe.

Hi we are trying to use inspec and we can not understand how to get it working can someone help us please.
 We are trying to scan esxi 7 servers and a vcsa server for compliance and apply the compliance controls via inspec.

### Describe the solution you'd like

Clear concise instructions to solve problem.

**Comment by HerbBoy** [comment]
Not speak out for VMware folks but figured id provide an answer since ive been using the project for a while.

@LunaireRae 

InSpec is the tool used to validate your compliance, it is not a tool that **applies** any lockdown. That is handled by PS scripts and Ansible.

The README for vSphere contains working [examples](https://github.com/vmware/dod-compliance-and-automation/blob/master/vsphere/7.0/vsphere/inspec/vmware-vsphere-7.0-stig-baseline/README.md)

Same goes for [VCSA ](https://github.com/vmware/dod-compliance-and-automation/blob/master/vsphere/7.0/vcsa/inspec/vmware-vcsa-7.0-stig-baseline/README.md)

Only difference you will find between the two is the "transport" or medium used to interact with the endpoints. Example being ESXi's use the VMware transport (-t vmware://) and VCSA uses the SSH transport (-t ssh://) which is simply how you interact with the endpoints.

InSpec is not a tool that can be run against multiple endpoints at a time. This is something you would need to write a wrapper for with say Ansible to invoke InSpec. More info on [InSpec CLI](https://docs.chef.io/inspec/cli/)

Note, something you will run into and I hope to add the automation for soon is with VCSA (you will run into this with Ansible lockdowns as well) your default VCSA shell when you attempt to SSH is that vmware menu thingy, so you will need to change the default shell in order for this to work, I used this [article](http://vcloud-lab.com/entries/vcenter-server/enable-access-to-the-vcsa-bash-shell-or-appliance-shell) before i automated it.
