### ISSUE TITLE
INSPEC: VCSA-70-000110, 268, 269, 270 fail on Windows

### ISSUE THREAD

**Issue by pbarrette** [vmware/dod-compliance-and-automation#127]
### Describe the bug

The controls VCSA-70-000110, VCSA-70-000268, VCSA-70-000269 and VCSA-70-000270 fail when executing inspec on a Windows system.

This is probably also true for any system using line endings other than LF.

### Reproduction steps

1. From a Windows system, execute an inspec scan for any of the above controls on a compliant system.

### Expected behavior

The scan should be marked as compliant.

### Additional context

VCSA-70-000110 is executing Get-VDISwitch and splitting the name with stdout.split("\n")
The remaining controls are doing the same, but also splitting on the results of Get-VDPortgroup.

In all cases, changing the split to a regex with an optional CR corrects the issue.
Thus, stdout.split("\n") becomes stdout.split(/\r?\n/)

**Comment by rlakey** [comment]
Fixed all of the potential output differences between running this on Windows/Linux and/or Powershell/Powershell Core in https://github.com/vmware/dod-compliance-and-automation/commit/f5f30858d63189f45e0465617a3a28ec67769c64

**Comment by pbarrette** [comment]
Not that I'm complaining, because this seems to work, but I was looking into the code a bit more and wondered if it would make more sense to replace `result.stdout` with `result.stdout.gsub("\r\n", "\n")` in `powercli_command.rb`?

**Comment by rlakey** [comment]
It could but I don't know what other ramifications that would have on other controls where this isn't a factor. It's really only a problem where we are splitting output into an array and only if there are spaces in the names which is why i didn't catch some of this.

stdout.split works fine with no modification if there are no spaces in the output strings.  As soon as a space is introduced it'll split on the space and the \r\n and \n.

I also didn't update all of the ESXi controls where we are gathering VMhost names because i don't believe those can have spaces.
