### ISSUE TITLE
Support release tags

### ISSUE THREAD

**Issue by r-eason** [vmware/dod-compliance-and-automation#203]
### Is your feature request related to a problem? Please describe.

I'm happy to use the code from master and a reference commit, but do you have any thoughts about tagging a stable release?

### Describe the solution you'd like

Add a tag for a releases.

### Additional context

I've looked through the history and there are commits with failed syntax changes on master. I'd feel more comfortable using a known-good tagged release against environments I maintain.

**Comment by rlakey** [comment]
Hi @r-eason the items that are failing the syntax check have an open issue here:  https://github.com/vmware/dod-compliance-and-automation/issues/156

Since it's been open a while with no attention I may just remove those particular playbooks but they are just failing due to newer ansible link updates but I agree I don't like that overall the pipeline is in a failed state.

I'll have to think about a release and if that makes sense with this style of repo.

**Comment by r-eason** [comment]
Thanks, I'll move forward referencing a commit hash, and I appreciate the work you've put into the project.

**Comment by rlakey** [comment]
We have just restructured the repo to support multiple versions of content in the master branch to remove the need for releases and other branches so closing this.  Also redid the linting workflows.
